name: power_lint
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Packages that use the lint must include the following pakcages in their dev_dependencies:
# custom_lint: ^0.8.1
# saropa_lints: ^4.5.0
